### ISSUE TITLE
Ability to see status of forwarded emails - are they processed or not

### ISSUE THREAD

**Issue by alexjv89** [cashflowy/cashflowy#110]
Cashflowy allows customers to forward email to a given address. Even if customer setups the auto forwarder, its difficult to know if the auto forwarder is setup right. 

In order to give customer confidence that the auto forwarded is setup right, there should be a page on cashflowy that shows the emails that we can received, the type of the email (auto forwarded or manually forwarded), the status of the email (is data extracted from it) and the data extracted from the email.

**Comment by aptro** [comment]
<img width="1194" alt="Screenshot 2019-04-13 at 2 24 24 PM" src="https://user-images.githubusercontent.com/10391409/56077279-f037ba00-5df7-11e9-815c-6ce1b57d8315.png">
Now user can see what all emails system able to parse and user can retry or reparse a forwarded mail.
