### ISSUE TITLE
View Transaction Details

### ISSUE THREAD

**Issue by aptro** [cashflowy/cashflowy#34]
Ability to dig deeper into a transaction. 

- Source of the transaction 
   -  Is it created by email   
   -  Is it created document
   -  Is it created by screen scraper
- View duplicate/similar transactions that can be merged.
- Ability to download the invoice for that transaction.

**Comment by alexjv89** [comment]
this needs to be done as part of document parsing..

**Comment by alexjv89** [comment]
![image](https://user-images.githubusercontent.com/2733923/53028957-e8116d00-348d-11e9-97ad-0677817bf64a.png)
the way splitwise handles more details is nice.. that style is preferred

**Comment by alexjv89** [comment]
preliminary implementation of details: 
![image](https://user-images.githubusercontent.com/2733923/53035762-2dd53200-349c-11e9-83df-8b95b06e9e9b.png)
when a transaction is created from email

![image](https://user-images.githubusercontent.com/2733923/53035810-49d8d380-349c-11e9-83bc-f7bdabc6fdc7.png)
manually created transaction 


![image](https://user-images.githubusercontent.com/2733923/53035647-ee0e4a80-349b-11e9-93c8-1a981d4158c3.png)
A transfer transaction is mentioned in 2 documents. Note - this transaction is still marked as an expense. It needs to be converted into a transaction. 

if a transaction is not mentioned by a parsed email or a document, then it is assumed that the transaction is manually created. 


Some sort of cached logging for the transaction might be useful.
