### ISSUE TITLE
Bull hung state detection

### ISSUE THREAD

**Issue by alexjv89** [cashflowy/cashflowy#56]
For now we dont really know why Bull/Kue is hanging often. 
Restarting the application server solves the hung state problem. 

There has to be a way to detect bull hung state and reset it. 

When they are detected late, there is usually a huge backlog of tasks pending.

**Comment by aptro** [comment]
more info:
https://optimalbits.github.io/bull/
<img width="945" alt="screenshot 2019-02-18 at 8 00 25 pm" src="https://user-images.githubusercontent.com/10391409/52957607-10c73300-33b8-11e9-8620-6a4eb17c5bb0.png">

**Comment by aptro** [comment]
The hung state issue was due to the lack of callback in one of the task. If the task is failed and somehow the callback is not called then bull goes into hung state.

This is fixed.
